#cloud-config
hostname: ${hostname}-${environment}
bootcmd:
  - echo "127.0.0.1 localhost" > /etc/hosts
locale: en_US.UTF-8
timezone: UTC
runcmd:
  - 'sudo yum update -y' 
  - 'sudo yum install java-1.8.0-openjdk.x86_64 -y' 
  - 'echo "export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk" |  sudo tee -a /etc/profile' 
  - 'echo "export JRE_HOME=/usr/lib/jvm/jre" | sudo tee -a /etc/profile'
  - 'sudo source /etc/profile'  
  - 'sudo ln -fs /usr/lib/jvm/jre-1.8.0-openjdk/bin/java /etc/alternatives/java' 
  - 'sudo ln -fs /usr/lib/jvm/jre-1.8.0-openjdk.x86_64 /etc/alternatives/jre'  
  - 'cd ~' 
  - 'sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo'  
  - 'sudo rpm --import http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key'  
  - 'sudo yum install git -y'   
  - 'sudo yum install jenkins -y'   
  - 'sudo yum install docker -y' 
  - 'sudo service jenkins start && sudo service docker start  && echo "All is well! :-)"'
  - 'sleep 120'
  - 'cd /tmp'
  - curl -O http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar && pass=`sudo cat /var/lib/jenkins/secrets/initialAdminPassword` && echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("tech-user","tech-pass")' | sudo java -jar jenkins-cli.jar -auth admin:$pass -s http://localhost:8080/ groovy = 
  - 'echo "services are now running'
final_message: "The system is up, after $UPTIME seconds"

